# Generated by Django 3.1.1 on 2020-09-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='country',
            new_name='capital',
        ),
    ]
